"""INDEX.md: every game in one table, generated from the records.

Never edited by hand: change a record and the index follows. It exists so a
person can see the whole inventory, and where each game stands, in one place.
"""

from __future__ import annotations

import json

from gen_inventory.schema import Record

#: What each status means to a reader. `covered` is the only one that says the
#: game is in the library; `dropped` is a game the gates turned away for good.
DISPOSITION = {
    "ported": "covered",
    "evaluated": "covered",
    "accepted": "covered",
    "ready": "queued",
    "blocked": "blocked",
    "duplicate": "dropped",
    "rejected": "dropped",
    "incomplete": "needs work",
    "candidate": "unchecked",
}

ORDER = ["covered", "queued", "blocked", "needs work", "unchecked", "dropped"]


def disposition(rec: Record) -> str:
    return DISPOSITION[rec.status]


def note(rec: Record) -> str:
    if rec.status == "duplicate":
        return f"duplicate of {rec.duplicate_of}"
    if rec.status == "blocked":
        return "blocked by " + ", ".join(rec.blocked_by)
    if rec.status in ("incomplete", "rejected"):
        return "; ".join(r.split(": ", 1)[-1] for r in rec.reasons)
    parts = []
    if rec.status == "ready":
        parts.append(f"value {rec.value}")
        if rec.family and rec.family != rec.id:
            parts.append(f"variant of {rec.family}")
        if rec.workarounds:
            parts.append("workaround: " + ", ".join(rec.workarounds))
        if rec.reward == "judged":
            parts.append("judged outcome")
    elif rec.port and rec.port != rec.source.get("ref"):
        parts.append(f"`{rec.port}`")
    return "; ".join(parts)


def source(rec: Record) -> str:
    s = rec.source
    link = s.get("url") or s.get("ref") or ""
    return f"[{s['kind']}]({link})" if link.startswith("http") else f"{s['kind']}: `{link}`"


def render(records: list[Record]) -> str:
    out = [
        "# Game inventory",
        "",
        "Generated by `python3 -m gen_inventory index`; edit the records in `data/inventory/`, not this file.",
        "",
    ]
    counts = {d: sum(disposition(r) == d for r in records) for d in ORDER}
    out.append(" · ".join(f"{n} {d}" for d, n in counts.items() if n))
    out += ["", "| id | game | description | source | rating | status | note |", "|---|---|---|---|---|---|---|"]
    for r in sorted(records, key=lambda r: (ORDER.index(disposition(r)), r.id)):
        cells = [f"`{r.id}`", r.name, r.summary, source(r), str(r.rating) if r.rating else "–", disposition(r), note(r)]
        out.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
    out.append("")
    return "\n".join(out)


def render_json(records: list[Record]) -> str:
    """INDEX.json: the same table for programs. One entry per game, the id unique."""
    ids = [r.id for r in records]
    if len(set(ids)) != len(ids):
        raise ValueError("duplicate ids in the inventory: " + ", ".join(sorted({i for i in ids if ids.count(i) > 1})))
    rows = [
        {
            "id": r.id,
            "name": r.name,
            "summary": r.summary,
            "source": r.source.get("url") or r.source.get("ref") or "",
            "rating": r.rating,
            "status": r.status,
            "disposition": disposition(r),
            "note": note(r),
            "family": r.family_key,
            "duplicate_of": r.duplicate_of,
        }
        for r in sorted(records, key=lambda r: r.id)
    ]
    return json.dumps(rows, indent=2) + "\n"
