"""Where to look for games: the registry of sources, and a model that proposes more.

A source is a website. A model may suggest sites and search phrases, but a
suggestion is only a line in a list until someone says otherwise:

    suggested   a model's idea; nothing reads it
    approved    a person agreed; waits for an adapter that can read the site
    crawling    has an adapter and is read on every crawl
    rejected    never again

So a model can widen the search for queries on a site already being crawled
(a search phrase is harmless), but never points the crawler at a new host by
itself. Every site and every phrase is kept once: the registry is what stops
a suggestion repeating, whether it came from a model or from a person.
"""

from __future__ import annotations

import json
import re
import urllib.parse
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

REGISTRY_PATH = Path(__file__).parent / "data" / "sources.json"

KINDS = ("encyclopedia", "catalogue", "papers", "textbook", "community", "code_repo", "other")
STATUSES = ("suggested", "approved", "crawling", "rejected")
#: Hosts that are for hosting or pasting files, not for reading about games.
DENIED_HOSTS = {
    "catbox.moe", "imgur.com", "imgbb.com", "pastebin.com", "gist.github.com", "file.io", "transfer.sh",
    "0x0.st", "tmpfiles.org", "gofile.io", "dpaste.org", "hastebin.com", "ix.io", "paste.ee", "sprunge.us",
    "anonfiles.com", "uguu.se",
}


class Completion(Protocol):
    def complete(self, prompt: str, system: str = "") -> str: ...


class SourceError(ValueError):
    pass


def host_of(url: str) -> str:
    """The site a URL belongs to: lowercase, no `www.`, https or http only."""
    parts = urllib.parse.urlparse(url.strip())
    host = (parts.hostname or "").lower().removeprefix("www.")
    if parts.scheme not in ("http", "https") or "." not in host:
        raise SourceError(f"not a web address: {url!r}")
    if any(host == d or host.endswith("." + d) for d in DENIED_HOSTS):
        raise SourceError(f"{host} hosts files; it is not a source of game rules")
    return host


def norm_query(q: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]+", " ", q.lower())).strip()


class Registry:
    """`data/sources.json`: every site and the phrases tried on it."""

    def __init__(self, path: Path = REGISTRY_PATH):
        self.path = Path(path)
        self.sources: list[dict] = []
        if self.path.exists():
            self.sources = json.loads(self.path.read_text())["sources"]

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps({"sources": self.sources}, indent=2) + "\n")

    def get(self, host: str) -> dict | None:
        return next((s for s in self.sources if s["host"] == host), None)

    def add_source(self, name: str, url: str, kind: str, why: str, origin: str, status: str = "suggested") -> tuple[dict, bool]:
        """Returns the entry and whether it is new."""
        host = host_of(url)
        if (have := self.get(host)) is not None:
            return have, False
        if kind not in KINDS:
            kind = "other"
        entry = {"host": host, "name": name.strip() or host, "url": url.strip(), "kind": kind, "status": status,
                 "origin": origin, "why": why.strip()[:300], "queries": [], "categories": []}
        self.sources.append(entry)
        self.save()
        return entry, True

    def add_query(self, host: str, q: str, origin: str) -> bool:
        """File a search phrase under a site. False if it is already there."""
        entry = self.get(host)
        if entry is None:
            raise SourceError(f"{host} is not in the registry")
        key = norm_query(q)
        if not key or any(norm_query(x["q"]) == key for x in entry["queries"]):
            return False
        entry["queries"].append({"q": q.strip(), "origin": origin})
        self.save()
        return True

    def set_status(self, host: str, status: str) -> dict:
        if status not in STATUSES:
            raise SourceError(f"status must be one of {', '.join(STATUSES)}")
        entry = self.get(host)
        if entry is None:
            raise SourceError(f"{host} is not in the registry")
        entry["status"] = status
        self.save()
        return entry

    def queries(self, host: str) -> list[str]:
        return [x["q"] for x in (self.get(host) or {}).get("queries", [])]

    def categories(self, host: str) -> list[str]:
        return list((self.get(host) or {}).get("categories", []))

    def render(self, yields: dict[str, Counter] | None = None) -> str:
        """SOURCES.md: one row per site, then the phrases tried on each."""
        yields = yields or {}
        out = ["# Sources", "",
               "Generated by the crawl and `python3 -m gen_inventory sources`; the list is `data/sources.json`.", "",
               "| site | kind | status | origin | why |", "|---|---|---|---|---|"]
        for s in self.sources:
            out.append(f"| [{s['host']}]({s['url']}) | {s['kind']} | {s['status']} | {s['origin']} | {s['why'].replace('|', '/')} |")
        for s in self.sources:
            if not (s["queries"] or s["categories"]):
                continue
            out += ["", f"## {s['host']}", ""]
            if s["categories"]:
                out.append("Categories: " + ", ".join(f"`{c}`" for c in s["categories"]))
                out.append("")
            if s["queries"]:
                out += ["| search phrase | origin | pages read | added |", "|---|---|---|---|"]
                for x in s["queries"]:
                    y = yields.get(f"query:{x['q']}", Counter())
                    out.append(f"| {x['q']} | {x['origin']} | {sum(y.values())} | {y.get('added', 0)} |")
        out.append("")
        return "\n".join(out)


def yields_from(log_entries) -> dict[str, Counter]:
    """Outcomes of the pages each category or phrase found, from the crawl log."""
    out: dict[str, Counter] = {}
    for e in log_entries:
        if e.get("via"):
            out.setdefault(e["via"], Counter())[e["outcome"]] += 1
    return out


# ----------------------------------------------------------------------
# Asking a model
# ----------------------------------------------------------------------

SYSTEM = """You help build an inventory of turn-based, text-only, multi-player strategy games, to train
language models on strategic reasoning: hidden information, bluffing, bidding, bargaining, opponent
modelling, planning. A crawler reads public web pages whose text states a game's rules.

Suggest where to look next. Reply with one JSON object and nothing else:

  {"sources": [{"name": "...", "url": "https://...", "kind": "<kind>", "why": "<one sentence>"}],
   "queries": [{"host": "<a site already listed as crawling>", "q": "<a search phrase>"}]}

kind is one of: """ + ", ".join(KINDS) + """.

Rules:
- We want turn-based strategy games. Skip sites about video games, real-time games or sports. Later steps
  judge each game in detail, so do not filter finely here.
- Only public pages that need no login and no payment. No file-hosting or paste sites.
- A source is a website (or one section of one) that lists or describes MANY games with rules or
  payoffs, not a single game's page. Say why it fits.
- Never repeat a site or a search phrase that is already listed below, even reworded.
- Prefer phrases that would find games unlike those already in the inventory, and games that need what
  the engine cannot yet express only if they are otherwise very good.
- Search phrases are for the sites marked crawling only."""


def prompt(registry: Registry, inventory_summary: str, yields: dict[str, Counter], n: int) -> str:
    lines = []
    for s in registry.sources:
        lines.append(f"- {s['host']} [{s['status']}] {s['name']}: {s['why']}")
        for x in s["queries"]:
            y = yields.get(f"query:{x['q']}", Counter())
            lines.append(f"    phrase {x['q']!r}: {sum(y.values())} pages read, {y.get('added', 0)} added")
        for c in s["categories"]:
            y = yields.get(f"category:{c}", Counter())
            lines.append(f"    category {c}: {sum(y.values())} pages read, {y.get('added', 0)} added")
    return (f"Already listed (do not repeat):\n" + "\n".join(lines) + f"\n\nThe inventory so far:\n{inventory_summary}\n\n"
            f"Suggest up to {n} new sources and up to {n} new search phrases.")


@dataclass
class Suggestions:
    new_sources: list[dict] = field(default_factory=list)
    new_queries: list[tuple[str, str]] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def suggest(completion: Completion, registry: Registry, inventory_summary: str, yields: dict[str, Counter],
            n: int = 6) -> Suggestions:
    from gen_inventory.crawl import first_json

    ask = prompt(registry, inventory_summary, yields, n)
    data = None
    for _ in range(2):
        try:
            data = first_json(completion.complete(ask, system=SYSTEM))
            break
        except ValueError as exc:
            ask += f"\n\nYour previous reply was refused: {exc}\nReply again with the JSON object only."
    if data is None:
        raise SourceError("the model gave no usable suggestion")

    got = Suggestions()
    for item in (data.get("sources") or [])[:n]:
        try:
            entry, new = registry.add_source(str(item.get("name", "")), str(item.get("url", "")),
                                             str(item.get("kind", "other")), str(item.get("why", "")), origin="model")
        except (SourceError, AttributeError) as exc:
            got.skipped.append(str(exc))
            continue
        (got.new_sources if new else got.skipped).append(entry if new else f"{entry['host']} is already listed")
    for item in (data.get("queries") or [])[:n]:
        try:
            host, q = host_of("https://" + str(item["host"]).strip().removeprefix("https://")), str(item["q"])
            entry = registry.get(host)
            if entry is None or entry["status"] not in ("crawling", "approved"):
                got.skipped.append(f"phrase {q!r}: {host} is not a site being crawled")
            elif registry.add_query(host, q, origin="model"):
                got.new_queries.append((host, q))
            else:
                got.skipped.append(f"phrase {q!r} is already listed")
        except (SourceError, KeyError, AttributeError) as exc:
            got.skipped.append(f"bad query: {exc}")
    return got
